[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]
auto-format = true

[[language]]
name = "css"
scope = "source.css"
injection-regex = "css"
file-types = ["css", "scss"]
block-comment-tokens = { start = "/*", end = "*/" }
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "tsx"
language-servers = ["typescript-language-server", "tailwindcss-ls"]
